Kurochka_Djanga/urls.py
from django.contrib import admin
from django.urls    import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',       include('main.urls')),
    path('polls/', include('Kurochka_Polls.urls'))
]

Kurochka_Polls/urls.py
from django.urls import path
from .           import views

app_name    = "Kurochka_Polls"
urlpatterns = [
    path('',                        views.IndexView.as_view(),   name = 'index'),
    path('<int:pk>/',               views.DetailView.as_view(),  name = 'detail'),
    path('<int:pk>/results',        views.ResultsView.as_view(), name = 'results'),
    path('<int:question_id>/vote/', views.vote,                  name = 'vote'),

]

main/urls.py
from django.urls import path
from .           import views


urlpatterns = [
    path('', views.home)
]

Kurochka_Pictures/models.py
from django.db import models

# Create your models here.

Kurochka_Polls/models.py
import datetime

from django.db    import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length = 200)
    publish_date  = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days = 1) <= self.publish_date <= now


class Choice(models.Model):
    question    = models.ForeignKey(Question, on_delete = models.CASCADE, )
    choice_text = models.CharField(max_length = 200)
    votes       = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text

main/models.py
from django.db import models

# Create your models here.

Kurochka_Pictures/views.py
from django.shortcuts import render

# Create your views here.

Kurochka_Polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http      import HttpResponse, HttpResponseRedirect, Http404
from django.urls      import reverse
from django.views     import generic
from django.utils     import timezone
from django.db.models import F


from .models          import Question, Choice


class IndexView(generic.ListView):
    template_name       = 'Kurochka_Polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Возвращает последние пять опубликованных опросов (Исключая те, что установлены к публикации в будущем)
        """
        return Question.objects.filter(publish_date__lte = timezone.now()).order_by('-publish_date')[:5]


class DetailView(generic.DetailView):
    model         = Question
    template_name = "Kurochka_Polls/detail.html"

    def get_queryset(self):
        """
        Исключаем опросы, которые ещё не были опубликованы
        :return:
        """
        return Question.objects.filter(publish_date__lte = timezone.now())


class ResultsView(generic.DetailView):
    model         = Question
    template_name = "Kurochka_Polls/results.html"

    def get_queryset(self):
        """
        Исключаем опросы, которые ещё не были опубликованы
        :return:
        """
        return Question.objects.filter(publish_date__lte = timezone.now())


def vote(request, question_id):
    question = get_object_or_404(Question, pk = question_id)

    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])

    except (KeyError, Choice.DoesNotExist):
        return render(request, 'Kurochka_Polls/detail.html', { 'question'      : question,
                                                               'error_message' : "Вы не выбрали ни одного варианта!" })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('Kurochka_Polls:results', args = (question.id, ) ))



# def index(request):
#     latest_question_list = Question.objects.order_by('-publish_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request, 'Kurochka_Polls/index.html', context)
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk = question_id)
#     return render(request, 'Kurochka_Polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk = question_id)
#     return render(request, 'Kurochka_Polls/results.html', {'question': question})
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk = question_id)
#
#     try:
#         selected_choice = question.choice_set.get(pk = request.POST['choice'])
#
#     except (KeyError, Choice.DoesNotExist):
#         render(request, 'Kurochka_Polls/index.html', {'question'     : question,
#                                                       'error_message': "Вы не выбрали ни одного варианта"})
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('Kurochka_Polls:results', args = (question.id,)))
pass

main/views.py
from django.shortcuts import render
from django.http      import HttpResponse


def home(request):
    return render(request, 'index.html')

Kurochka_Polls/templates/Kurochka_Polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Опрос # {{ question.id }}</title>
</head>
<body>

<div>Вы видите опрос #{{ question.id }}</div>
<br><br>
<form action="{% url 'Kurochka_Polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
</body>
</html>

Kurochka_Polls/templates/Kurochka_Polls/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Курочкин опросник</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'Kurochka_Polls/style.css' %}">
    </head>
    <body>
        <div class="title">Это - главная страница опросника Курочки!</div>
        <br>
        <br>
        <div class="questions">
            {% if latest_question_list %}
                <ul>
                {% for question in latest_question_list %}
                    <li><a href="{% url 'Kurochka_Polls:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
                </ul>
            {% else %}
                <p>Нет доступных опросов.</p>
            {% endif %}
        </div>
    </body>
</html>

Kurochka_Polls/templates/Kurochka_Polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Результаты опроса #{{ question.id }}</title>
</head>
<body>
<div>Вы смотрите на результаты опроса #{{ question.id }}.</div>
<h1>Опрос: {{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'Kurochka_Polls:detail' question.id %}">Проголосовать снова?</a>
</body>
</html>

main/templates/index.html
<html>
    <head>
        <meta charset="utf-8">
        <title>Login-page</title>
        {% load static %}
        <link href="{% static 'main/style.css' %}" media="all" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <div class="welcome">Добро пожаловать на сервер Курочки Джанги!</div>
        <div class="login">
             <form method="post">
                 <table align="center" class="log">
                     <tr>
                         <td>
                             <strong>Логин:</strong>
                         </td>
                         <td>
                             <input maxlength="25" size="40" name="login" type="text">
                         </td>
                     </tr>

                     <tr>
                         <td>
                             <strong>Пароль:</strong>
                         </td>
                         <td>
                             <input type="password" maxlength="25" size="40" name="pass">
                         </td>
                     </tr>
                 </table>
                 <br><input name="go" type="submit" value="Войти">
             </form>
         </div>

        {% if invalid_password %}
        <div class="additional">
            <strong>Неверный пароль!</strong>
        </div>
        {% endif %}

        {% if login_block %}
        <div class="additional">
            <strong>Вход для данного логина заблокирован!</strong>
        </div>
        {% endif %}

    </body>
</html>